services:
  backend:
    build: ./back
    container_name: epl_backend
    ports:
      - "8000:8000"

  frontend:
    build: ./front
    container_name: epl_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend